# To automatically trigger the workflow on tagging
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: build & publish chrome extension
    runs-on: ubuntu-latest
    steps:
      - uses: vimtor/action-zip@v1.2
        with:
          files: manifest.json
          dest: result.zip
      - uses: Klemensas/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_EXTENSION_SECRET }}
          file-name: './result.zip'
          app-id: 'pligoajaaggbghgopjdmkfbnaodknplm'
          publish: true
